"""create User, Makeup, and favorites tables

Revision ID: 4027383191e6
Revises: b77e594e4b7c
Create Date: 2023-08-27 13:29:46.497479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4027383191e6'
down_revision: Union[str, None] = 'b77e594e4b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makeups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_makeup_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('makeup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['makeup_id'], ['makeups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'makeup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_makeup_favorites')
    op.drop_table('users')
    op.drop_table('makeups')
    # ### end Alembic commands ###
